# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  filepath: './print.sh'

steps:
- task: Bash@3
  inputs:
    filePath: '$(filepath)'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription(677e2958-8c03-4ec0-9cb2-a8f3d7a4b5ec)'
    KeyVaultName: 'plocuesazkv04'
    SecretsFilter: '*'
    RunAsPreJob: false

- bash: echo '$(ploceuskeyvaultsecret000001)'